import type { NextConfig } from "next";
import { withBotId } from "botid/next/config";

const nextConfig: NextConfig = {
  images: {
    /*
      NEXT 16 NARROWED THIS TO [75] AND IT FAILS SILENTLY.

      `images.qualities` used to allow any value; it now defaults to [75]
      alone, and a `quality` prop outside the list is COERCED to the nearest
      allowed value rather than erroring. So `quality={55}` on the homepage
      hero renders at 75, the bytes never drop, and nothing anywhere says why.

      55 is here for one image: the hero photograph sits under a graphite ramp
      running 0.97 to 0.45 across its whole width, so most of the detail q75
      pays to encode is destroyed by the scrim before anyone sees it. Measured
      difference between q75 and q45 on that frame is 2.08/255 per channel
      BEFORE the ramp is applied. It is not a general licence to drop quality —
      an unscrimmed photograph at 55 looks like an unscrimmed photograph at 55.
    */
    qualities: [55, 75],
    remotePatterns: [
      // Luma event cover art, served off their CDN.
      { protocol: "https", hostname: "images.lumacdn.com" },
      { protocol: "https", hostname: "cdn.lu.ma" },
      // Firebase Storage (brand assets, member media).
      { protocol: "https", hostname: "firebasestorage.googleapis.com" },
      // The /since-2011 photo wall. Thumbnails are generated by
      // lib/gallery-sync.ts and served from public Vercel Blob.
      { protocol: "https", hostname: "*.public.blob.vercel-storage.com" },
      // Google account avatars, shown in the admin shell.
      { protocol: "https", hostname: "lh3.googleusercontent.com" },
    ],
  },
  async redirects() {
    // Paths from the coworking-era geekdom.com. `permanent: true` is a 308.
    //
    // CAUTION: this matcher is case-INSENSITIVE, so a source that differs from
    // its destination only by case matches its own destination and 308s in a
    // loop forever. Every source below differs by more than case; case-only
    // rules belong in proxy.ts, which compares exactly.
    return [
      // /membership BECAME /club when the nav was rebuilt around the two
      // engines. This is the only redirect here whose source was a live page
      // on THIS site rather than on the old one, which makes it the one most
      // likely to be followed by a real person with a real bookmark — and by
      // Google, which has the old URL indexed with its own share card.
      { source: "/membership", destination: "/club", permanent: true },
      // /the-floor was retired into the Club's clubhouse section. Half of
      // it duplicated /club and /events; the photography and the
      // wayfinding moved. Same reasoning as /membership above — this was
      // a live page on THIS site, indexed, with its own share card.
      { source: "/the-floor", destination: "/club", permanent: true },
      // /whats-changing held the members letter announcing the move from
      // coworking to a club. Geekdom asked for the letter and its page to
      // come out. Same class as the two above — a live page on THIS site,
      // in the sitemap, with its own share card, and linked from the
      // homepage, /since-2011 and the 404 — so it 308s rather than 404s for
      // anyone holding the URL.
      { source: "/whats-changing", destination: "/club", permanent: true },

      // Coworking is sunsetting. Anyone landing on the old membership or
      // pricing pages should get the club's story, not a 404.
      { source: "/join", destination: "/club", permanent: true },
      { source: "/pricing", destination: "/club", permanent: true },
      { source: "/coworking", destination: "/club", permanent: true },
      { source: "/why-geekdom", destination: "/club", permanent: true },
      { source: "/tour", destination: "/club", permanent: true },

      // The Studio's two most guessable URLs. It has no open application, so
      // /apply would be the wrong destination — the page explains why.
      { source: "/venture", destination: "/studio", permanent: true },
      { source: "/community-fund", destination: "/studio", permanent: true },

      // /events and /faq CAME OUT at Geekdom's request — neither is in
      // `Source Copy v1`'s sitemap. The calendar lives on Luma (the homepage's
      // "This month in the Club" links there); the FAQ's membership answers
      // live on /club.
      //
      // Luma is TEMPORARY (307), not permanent: it's another company's URL
      // and could change, and a 308 is cached by browsers forever. Kept in
      // step with LUMA_CALENDAR_URL in lib/site.ts by hand — this file
      // doesn't import app code.
      { source: "/events", destination: "https://luma.com/geekdom", permanent: false },
      { source: "/events/:slug*", destination: "https://luma.com/geekdom", permanent: false },
      { source: "/faq", destination: "/club", permanent: true },

      // Programs pointed at /events; straight to the calendar now, rather
      // than a two-hop chain through a redirect.
      { source: "/programs", destination: "https://luma.com/geekdom", permanent: false },
      { source: "/programs/:slug*", destination: "https://luma.com/geekdom", permanent: false },
      { source: "/incubator", destination: "https://luma.com/geekdom", permanent: false },

      // These pointed at /whats-changing, which itself 308s to /club — a
      // chain to the wrong place. The pages they were guessing at exist now.
      { source: "/about-us", destination: "/about", permanent: true },
      { source: "/press", destination: "/media", permanent: true },

      // NOT redirected, on purpose: the old blog archive and its ~dozens of
      // posts. None has a counterpart here, and pointing them all at the
      // homepage is what Google reads as a soft 404. A clean 404 is honest.
    ];
  },
};

// withBotId injects the client-side challenge script and the proxy rewrites
// BotID needs. Without this wrapper, `checkBotId()` has nothing to verify
// against and the protection silently does nothing.
export default withBotId(nextConfig);
